version: "3.8"

services:
  app:
    container_name: app.eaws
    build:
      context: ./
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db.eaws
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
